// <auto-generated />
using EfMigrationIssue;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfMigrationIssue.Migrations
{
    [DbContext(typeof(SampleContext))]
    [Migration("20180905011428_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EfMigrationIssue.Entities.Classroom", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("EfMigrationIssue.Entities.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<string>("ClassroomId")
                        .HasMaxLength(32);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("EfMigrationIssue.Entities.Teacher", b =>
                {
                    b.HasOne("EfMigrationIssue.Entities.Classroom", "Classroom")
                        .WithMany("Teachers")
                        .HasForeignKey("ClassroomId");
                });
#pragma warning restore 612, 618
        }
    }
}
